blank_issues_enabled: false
contact_links:
  - name: Ideas
    url: https://github.com/rpothin/servicebus-csharp-function-dataverse/discussions/categories/ideas
    about: Please suggest ideas to improve this repository here.
  - name: Questions
    url: https://github.com/rpothin/servicebus-csharp-function-dataverse/discussions/categories/q-a
    about: Please ask and answer questions here.